---
version: '3.7'
services:
  example-percona-server:
    build:
      context: .
      dockerfile: Dockerfile.Percona
    container_name: example-percona-server
    networks:
      - example-network
    environment:
      - PERCONA_TEST_POSTGRES_ADDR=example-external-postgres
      - PERCONA_TEST_POSTGRES_DBNAME=__DATABASE__
      - PERCONA_TEST_POSTGRES_USERNAME=__USER__
      - PERCONA_TEST_POSTGRES_DBPASSWORD=__PASSWORD__
      - PERCONA_TEST_POSTGRES_SSL_MODE=__SSL_MODE__
      - PERCONA_TEST_POSTGRES_SSL_CA_PATH=/percona-server-certificates/certificate_authority.crt
      - PERCONA_TEST_POSTGRES_SSL_KEY_PATH=/percona-server-certificates/percona_server.key
      - PERCONA_TEST_POSTGRES_SSL_CERT_PATH=/percona-server-certificates/percona_server.crt
      - PMM_DEBUG=1
      - PERCONA_TEST_TELEMETRY_INTERVAL=10s
      - PERCONA_TEST_TELEMETRY_DISABLE_START_DELAY=1
      - PERCONA_TEST_TELEMETRY_RETRY_BACKOFF=10s
      - PERCONA_TEST_PMM_DISABLE_BUILTIN_POSTGRES=__PMM_DISABLE_BUILTIN_POSTGRES__
      - GF_DATABASE_URL=postgres://__GRAFANA_USER__:__GRAFANA_PASSWORD__@example-external-postgres:5432/__GRAFANA_DATABASE__
      - GF_DATABASE_SSL_MODE=__SSL_MODE__
      - GF_DATABASE_CA_CERT_PATH=/grafana-certificates/certificate_authority.crt
      - GF_DATABASE_CLIENT_KEY_PATH=/grafana-certificates/grafana.key
      - GF_DATABASE_CLIENT_CERT_PATH=/grafana-certificates/grafana.crt

  example-external-postgres:
    build:
      context: .
      dockerfile: Dockerfile.Postgres
    container_name: example-external-postgres
    networks:
      - example-network
    environment:
      - POSTGRES_PASSWORD=example-root-password
    command: |
      postgres 
      -c shared_preload_libraries=pg_stat_statements 
      -c pg_stat_statements.max=10000 
      -c pg_stat_statements.track=all 
      -c pg_stat_statements.save=off 
      __WITH_SSL__ 
      -c ssl_ca_file=/external-postgres-certificates/certificate_authority.crt 
      -c ssl_cert_file=/external-postgres-certificates/external_postgres.crt 
      -c ssl_key_file=/external-postgres-certificates/external_postgres.key
      __WITH_HBA__
  
networks:
  example-network:
    name: example-network