CREATE DATABASE "__DATABASE__";
CREATE USER "__USER__" WITH PASSWORD '__PASSWORD__';
GRANT ALL PRIVILEGES ON DATABASE "__DATABASE__" TO "__USER__";
\c __DATABASE__;
CREATE EXTENSION pg_stat_statements;
CREATE DATABASE "__GRAFANA_DATABASE__";
CREATE USER "__GRAFANA_USER__" WITH PASSWORD '__GRAFANA_PASSWORD__';
GRANT ALL PRIVILEGES ON DATABASE "__GRAFANA_DATABASE__" TO "__GRAFANA_USER__";
