CREATE DATABASE "__DATABASE__";
CREATE USER "__USER__" LOGIN PASSWORD '__PASSWORD__';
GRANT ALL PRIVILEGES ON DATABASE "__DATABASE__" TO "__USER__";
\c __DATABASE__;
CREATE EXTENSION pg_stat_statements;